import {
  Layout,
  Type,
  ImageIcon,
  Grid,
  Briefcase,
  FileText,
  MousePointer,
  Layers,
  Users,
  LucideIcon,
} from 'lucide-react';

export interface SectionTypeDefinition {
  type: string;
  label: string;
  description: string;
  icon: LucideIcon;
  color: string;
  defaultVariant: string;
  supportsVariants: boolean;
  fieldOrder?: string[];
}

export const SECTION_REGISTRY: SectionTypeDefinition[] = [
  {
    type: 'hero',
    label: 'Hero Banner',
    description: 'Main brand message and primary CTA',
    icon: Layout,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: true,
  
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'title',
      'subtitle',
      'primaryCta',
      'secondaryCta',
      'image'
    ],
  },
  {
    type: 'trusted-brands',
    label: 'Brand Trust',
    description: 'Client logos and partner grid',
    icon: Grid,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'intro',
    label: 'Intro Text',
    description: 'Mission statement and key metrics',
    icon: Type,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'heading',
      'subheading',
      'cta'
    ],
  },
  {
    type: 'services',
    label: 'Services Grid',
    description: 'Core business offerings and solutions',
    icon: Briefcase,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: true,
    fieldOrder: ['heading', 'subheading', 'services'],
  },
  {
    type: 'industries',
    label: 'Industries',
    description: 'Vertical specific solution blocks',
    icon: ImageIcon,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'subheading', 'description', 'industries', 'viewAllCta'],
  },
  {
    type: 'why-ess',
    label: 'Value Prop',
    description: 'Unique selling points and differentiators',
    icon: MousePointer,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'image1', 'image2', 'image3', 'points'],
  },
  {
    type: 'portfolio',
    label: 'Portfolio',
    description: 'Case studies and project highlights',
    icon: Layers,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'subheading', 'projects', 'viewAllCta'],
  },
  {
    type: 'blog',
    label: 'Resources',
    description: 'Latest news and thought leadership',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'subheading', 'viewAllCta'],
  },
  {
    type: 'rich_text',
    label: 'Rich Text',
    description: 'Flexible HTML content block',
    icon: FileText,
    color: 'bg-slate-50 text-slate-400',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'erp-hero',
    label: 'ERP Hero',
    description: 'Header block for ERP overview',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeText',
      'badgeColor',
      'titleText',
      'titleColor',
      'titleSecondaryColor',
      'descriptionText',
      'descriptionColor',
      'button1Text',
      'button1Color',
      'button1BgColor',
      'button1Url', 'button1FormType',
      'button2Text',
      'button2Color',
      'button2BgColor',
      'button2Url', 'button2FormType',
      'image'
    ],
  },
  {
    type: 'erp-intro',
    label: 'ERP Overview Intro',
    description: 'General corporate intro text for ERP',
    icon: Type,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description'],
  },
  {
    type: 'erp-modules',
    label: 'ERP Modules Grid',
    description: 'Core functional capabilities grid',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'subheading', 'modules'],
  },
  {
    type: 'erp-features',
    label: 'ERP Tabbed Features',
    description: 'Interactive selector for technical capabilities',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'subheading', 'features'],
  },
  {
    type: 'erp-value',
    label: 'ERP Business Value',
    description: 'Grid showcasing business capabilities',
    icon: MousePointer,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'badgeText', 'values'],
  },
  {
    type: 'erp-transform',
    label: 'ERP Workflow Stack',
    description: 'Vertical panels for strategic benefits',
    icon: FileText,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'items'],
  },
  {
    type: 'retail-hero',
    label: 'Retail Hero',
    description: 'Header block for Retail ERP overview',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'buttonBgColor',
      'buttonText',
      'buttonTextColor',
      'buttonUrl', 'buttonFormType',
      'image'
    ],
  },
  {
    type: 'retail-nurture',
    label: 'Retail Nurture',
    description: 'Nurture your business section',
    icon: Type,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'title',
      'paragraphs',
      'images',
      'whyImagePath',
      'whyTitle',
      'whyParagraph'
    ],
  },
  {
    type: 'retail-features',
    label: 'Retail Features',
    description: 'Dark-themed feature showcase',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-operations',
    label: 'Retail Operations Grid',
    description: 'Grid showcasing POS operations',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-mobile-dashboard',
    label: 'Retail Mobile Dashboard',
    description: 'Interactive accordion for modules',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-clients',
    label: 'Retail Clients',
    description: 'Brand trust and client logos',
    icon: ImageIcon,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'autoScroll', 'logos'],
  },
  {
    type: 'retail-why-erp',
    label: 'Retail Why ERP',
    description: 'Detailed section explaining why ebizframe ERP is chosen for retail.',
    icon: Layers,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'mfg-hero',
    label: 'Manufacturing Hero',
    description: 'Hero block for Manufacturing template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'primaryButtonBgColor',
      'primaryButtonText',
      'primaryButtonTextColor',
      'primaryButtonUrl',
      'secondaryButtonBgColor',
      'secondaryButtonText',
      'secondaryButtonTextColor',
      'secondaryButtonUrl',
      'image'
    ],
  },
  {
    type: 'mfg-icons',
    label: 'Manufacturing Icons Row',
    description: 'Icons showcasing manufacturing benefits',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['tabs']
  },
  {
    type: 'mfg-demand',
    label: 'Manufacturing Connect Demand',
    description: 'Connect demand section',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'paragraph1', 'paragraph2'],
  },
  {
    type: 'mfg-process',
    label: 'Manufacturing Process Flow',
    description: 'Manufacturing process flow steps',
    icon: Layout,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['sectionTitle', 'sectionSubtitle', 'sectionDescription', 'processes'],
  },
  {
    type: 'mfg-efficiency',
    label: 'Manufacturing Efficiency Dash',
    description: 'Efficiency dashboard block',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['sectionTitle', 'sectionSubtitle', 'description', 'metrics', 'image'],
  },
  {
    type: 'mfg-models',
    label: 'Manufacturing Operating Models',
    description: 'Operating models grid block',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['sectionTitle', 'sectionSubtitle', 'sectionDescription', 'models'],
  },
  {
    type: 'employee-spotlight-hero',
    label: 'Employee Spotlight Hero',
    description: 'Hero section for employee spotlight',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3','badge', 'title', 'description', 'image'],
  },
  {
    type: 'employee-spotlight-cards',
    label: 'Employee Spotlight Cards',
    description: 'Cards showcasing employee stories',
    icon: Users,
    color: 'bg-pink-50 text-pink-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['employees'],
  },
  {
    type: 'career-hero',
    label: 'Career Hero',
    description: 'Hero block for Career template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'bgImage', 'ctaText', 'title', 'description'],
  },
  {
    type: 'career-why-join',
    label: 'Career Why Join',
    description: 'Why Join ESS section',
    icon: MousePointer,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'tag', 'mapImage', 'stats'],
  },
  {
    type: 'career-offices',
    label: 'Career Offices',
    description: 'Global offices grid',
    icon: Grid,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-experience',
    label: 'Career Experience',
    description: 'Software experience block',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'tag', 'products'],
  },
  {
    type: 'career-perks',
    label: 'Career Perks',
    description: 'Perks and benefits grid',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'tag', 'perks'],
  },
  {
    type: 'career-life',
    label: 'Career Life',
    description: 'Life Beyond Code gallery',
    icon: ImageIcon,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'job-detail-content',
    label: 'Job Detail Content',
    description: 'Main content and application form for a job detail page',
    icon: FileText,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'aboutTitle',
      'aboutText',
      'sections',
      'formHeader',
      'formSubheader'
    ],
  },
  {
    type: 'career-positions',
    label: 'Career Open Positions',
    description: 'Open job positions list',
    icon: Briefcase,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle'],
  },
  {
    type: 'career-cta',
    label: 'Career CTA',
    description: 'Call to action for career',
    icon: Layout,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'ctaText', 'pdfUrl'],
  },
  {
    type: 'blog-list-block',
    label: 'Blog List Section',
    description: 'Interactive listing section for news & resources with sidebar filters',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['badgeText', 'headingText', 'subheadingText', 'bgImage', 'topics', 'industries'],
  },
  {
    type: 'privacy-policy-block',
    label: 'Privacy Policy Block',
    description: 'Rich text content page for Privacy Policy and Terms of Use documents',
    icon: FileText,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'contentHtml'],
  },
  {
    type: 'blog-detail-block',
    label: 'Blog Detail Content',
    description: 'Rich detail view of an article including reconciliation diagram and highlight panels',
    icon: FileText,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'quality-hero',
    label: 'Quality Hero',
    description: 'Hero banner for Quality Policy template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'title',
      'description',
      'image'
    ],
  },
  {
    type: 'quality-content',
    label: 'Quality Content',
    description: 'Detailed content blocks for Quality Policy certifications and text',
    icon: FileText,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'testimonials-block',
    label: 'Testimonials Section',
    description: 'Dynamic customer testimonials listing with filter sidebar',
    icon: Layers,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'case-study-detail',
    label: 'Case Study Detail Content',
    description: 'Detailed layout for Case Studies including overview, challenges, solutions, and results',
    icon: FileText,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'hospital-hero',
    label: 'Hospital Hero',
    description: 'Header block for Hospital Management overview',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'primaryButtonBgColor',
      'primaryButtonText',
      'primaryButtonTextColor',
      'primaryButtonUrl',
      'secondaryButtonBgColor',
      'secondaryButtonText',
      'secondaryButtonTextColor',
      'secondaryButtonUrl',
      'image'
    ],
  },
  {
    type: 'hospital-overview',
    label: 'Hospital Overview',
    description: 'Overview grid for Hospital Management',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'cards'],
  },
  {
    type: 'hospital-features',
    label: 'Hospital Features',
    description: 'Features grid and image collage',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'features', 'image1', 'image2', 'image3'],
  },
  {
    type: 'hospital-regulatory',
    label: 'Hospital Regulatory',
    description: 'Regulatory compliance text and image collage',
    icon: FileText,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'points', 'image1', 'image2', 'image3'],
  },
  {
    type: 'hospital-tech-specs',
    label: 'Hospital Tech Specs',
    description: 'Technical specs text and image collage',
    icon: Layers,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'specs', 'image1', 'image2', 'image3'],
  },
  {
    type: 'staffing-hero',
    label: 'Staffing Hero',
    description: 'Header block for Staffing Services',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'buttonBgColor',
      'buttonText',
      'buttonTextColor',
      'buttonUrl', 'buttonFormType',
      'image'
    ],
  },
  {
    type: 'staffing-augmentation',
    label: 'Staffing Augmentation',
    description: 'Text block for Staffing Augmentation',
    icon: FileText,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'paragraph1', 'paragraph2'],
  },
  {
    type: 'staffing-technologies',
    label: 'Staffing Technologies',
    description: 'Technologies grid for Staffing',
    icon: Grid,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'columns'],
  },
  {
    type: 'staffing-why-ess',
    label: 'Staffing Why ESS',
    description: 'Why choose ESS for Staffing',
    icon: Layers,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'pills', 'image'],
  },
  {
    type: 'staffing-benefits',
    label: 'Staffing Benefits',
    description: 'Benefits of Staff Augmentation',
    icon: Layers,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'description', 'cards'],
  },
  {
    type: 'about-us-hero',
    label: 'About Us Hero',
    description: 'Main hero section for About Us',
    icon: Layout,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['subtitle', 'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'bgImage', 'title', 'description', 'items'],
  },
  {
    type: 'about-us-company-intro',
    label: 'Company Intro',
    description: 'Introduction and who we are',
    icon: Users,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['subtitle', 'title', 'description', 'description2', 'items', 'image'],
  },
  {
    type: 'about-us-mission-vision',
    label: 'Mission & Vision',
    description: 'Company purpose and direction',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'about-us-services-overview',
    label: 'Services Overview',
    description: 'Core offerings and solutions',
    icon: Briefcase,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['heading', 'items'],
  },
  {
    type: 'about-us-transformation-section',
    label: 'Transformation',
    description: 'Legacy to modernity and upgrades',
    icon: Layers,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'items'],
  },
  {
    type: 'about-us-why-ess',
    label: 'Why Trust Us',
    description: 'Core strengths and reasons to choose us',
    icon: Layout,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'items'],
  },
  {
    type: 'about-us-cta',
    label: 'About Us CTA',
    description: 'Call to action for About Us',
    icon: MousePointer,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'buttonText', 'pdfUrl'],
  },
  {
    type: 'contact-hero',
    label: 'Contact Hero',
    description: 'Hero section for the Contact Us page',
    icon: Layout,
    color: 'bg-[#4B2A63]/5 text-[#4B2A63]',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor'
    ],
  },
  {
    type: 'contact-form-faq',
    label: 'Contact Form & FAQ',
    description: 'Contact message form and FAQ list',
    icon: FileText,
    color: 'bg-[#4B2A63]/5 text-[#4B2A63]',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'formTitle',
      'formDescription',
      'disclaimerText',
      'faqTitle',
      'faqs'
    ],
  },
  {
    type: 'contact-locations',
    label: 'Contact Locations',
    description: 'Global office locations map and details',
    icon: Layout,
    color: 'bg-[#4B2A63]/5 text-[#4B2A63]',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'backgroundImageUrl',
      'title',
      'description',
      'image',
      'locations'
    ],
  },
  {
    type: 'job-detail-hero',
    label: 'Job Detail Hero',
    description: 'Header banner for career job details page',
    icon: Layout,
    color: 'bg-[#4B2A63]/5 text-[#4B2A63]',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'buttonText',
      'buttonTextColor',
      'buttonArrowColor',
      'tag1BgColor',
      'tag1Text',
      'tag1TextColor',
      'tag2BgColor',
      'tag2Text',
      'tag2TextColor',
      'titleText',
      'titleTextColor',
      'items'
    ],
  },
  {
    type: 'judicial-hero',
    label: 'Judicial Hero',
    description: 'Header block for Judicial Automation',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'buttonBgColor',
      'buttonText',
      'buttonTextColor',
      'buttonUrl', 'buttonFormType',
      'image'
    ],
  },
  {
    type: 'judicial-overview',
    label: 'Judicial Overview',
    description: 'Overview block for Judicial Automation',
    icon: FileText,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'heading',
      'description',
      'cards'
    ],
  },
  {
    type: 'judicial-features',
    label: 'Judicial Features',
    description: 'Features block for Judicial Automation',
    icon: Layout,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'sideImage',
      'heading',
      'description',
      'features'
    ],
  },
  {
    type: 'ass-hero',
    label: 'ASS Hero',
    description: 'Hero banner for After Sales Service template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'button1BgColor',
      'button1BorderColor',
      'button1Text',
      'button1TextColor',
      'button1Url', 'button1FormType',
      'button2BgColor',
      'button2BorderColor',
      'button2Text',
      'button2TextColor',
      'button2Url', 'button2FormType',
      'image'
    ],
  },
  {
    type: 'ass-intro',
    label: 'ASS Intro',
    description: 'Intro overview for After Sales Service',
    icon: Type,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'paragraphs'],
  },
  {
    type: 'ass-functionalities',
    label: 'ASS Functionalities',
    description: 'Functionalities checklist with image',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['badgeIcon', 'badgeText', 'title', 'items', 'image'],
  },
  {
    type: 'ass-benefits',
    label: 'ASS Benefits',
    description: 'Benefits with center image and left/right items',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'image', 'leftItems', 'rightItems'],
  },
  {
    type: 'ass-enterprise',
    label: 'ASS Enterprise',
    description: 'Enterprise features card grid',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'image', 'cards'],
  },
  {
    type: 'ass-stats',
    label: 'ASS Stats',
    description: 'Stats section with metrics grid',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['stats'],
  },
  {
    type: 'ass-process',
    label: 'ASS Process',
    description: 'Process flow steps',
    icon: Layers,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'steps'],
  },
  {
    type: 'ass-why-choose',
    label: 'ASS Integrations',
    description: 'Apps and integrations section with side image',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['badgeText', 'title', 'description', 'image'],
  },
  {
    type: 'ass-features-grid',
    label: 'ASS Integrations Directory',
    description: 'Interactive category directory of integration tools',
    icon: Grid,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'categories'],
  },
  {
    type: 'ass-cta',
    label: 'ASS CTA',
    description: 'Call to action banner',
    icon: MousePointer,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'buttonText',
      'buttonBgColor',
      'buttonTextColor',
      'pdfUrl'
    ],
  },
  {
    type: 'ass-clients',
    label: 'ASS Clients',
    description: 'Client logos strip',
    icon: ImageIcon,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'logos'],
  },
  {
    type: 'ass-experience',
    label: 'ASS Experience & Loyalty',
    description: 'Video or image showcase section with file size limits',
    icon: ImageIcon,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'mediaUrl', 'videoUrl'],
  },
  {
    type: 'aom-hero',
    label: 'AOM Hero',
    description: 'Hero section for Mobile App Overview template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'button1BgColor',
      'button1BorderColor',
      'button1Text',
      'button1TextColor',
      'button1Url', 'button1FormType',
      'button2BgColor',
      'button2BorderColor',
      'button2Text',
      'button2TextColor',
      'button2Url', 'button2FormType',
      'image'
    ],
  },
  {
    type: 'aom-solutions',
    label: 'AOM Mobility Solutions',
    description: 'Key solutions and cards list with left illustration image',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'image', 'items'],
  },
  {
    type: 'aom-workspace',
    label: 'AOM Workspace Tabber',
    description: 'Interactive parent-child tabbed operations list',
    icon: Layers,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'categories'],
  },
  {
    type: 'fmcg-hero',
    label: 'FMCG Hero',
    description: 'Hero section for FMCG template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'buttonBgColor',
      'buttonBorderColor',
      'buttonText',
      'buttonTextColor',
      'buttonUrl', 'buttonFormType',
      'image'
    ],
  },
  {
    type: 'fmcg-logos',
    label: 'FMCG Logos',
    description: 'ERP logos strip for FMCG template',
    icon: ImageIcon,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['autoScroll', 'logos'],
  },
  {
    type: 'fmcg-overview',
    label: 'FMCG Overview',
    description: 'Overview content section with image for FMCG template',
    icon: FileText,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'paragraphs', 'image'],
  },
  {
    type: 'fmcg-tabs',
    label: 'FMCG Persona Tabs',
    description: 'Interactive persona tab switcher with questions and dashboard screenshot for FMCG template',
    icon: Layers,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'tabs'],
  },
  {
    type: 'fmcg-action',
    label: 'FMCG AI Action Steps',
    description: 'Steps cards listing AI capabilities in BI for FMCG template',
    icon: Grid,
    color: 'bg-orange-50 text-orange-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'cards'],
  },
  {
    type: 'fmcg-impact',
    label: 'FMCG Business Impact',
    description: 'Measurable impact metrics strip for FMCG template',
    icon: ImageIcon,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'cards'],
  },
  {
    type: 'fmcg-challenges',
    label: 'FMCG Leader Challenges',
    description: 'Grid of challenges faced by FMCG decision makers',
    icon: FileText,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'cards'],
  },
  {
    type: 'fmcg-empower',
    label: 'FMCG BI Empowerment',
    description: 'Grid of BI solutions and advantages for FMCG template',
    icon: Grid,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'cards'],
  },
  {
    type: 'fmcg-use-cases',
    label: 'FMCG BI Use Cases',
    description: 'Pill tabbed list of FMCG operations use cases',
    icon: Layers,
    color: 'bg-[#4B2A63]/5 text-[#4B2A63]',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'tabs'],
  },
  {
    type: 'fmcg-integrations',
    label: 'FMCG Data Integrations',
    description: 'Grid of integrated data sources for FMCG template',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'cards'],
  },
  {
    type: 'fmcg-faq',
    label: 'FMCG FAQ Accordion',
    description: 'Accordion listing of frequently asked questions for FMCG template',
    icon: FileText,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'faqs'],
  },
  {
    type: 'fmcg-cta',
    label: 'FMCG Transformation CTA',
    description: 'Call to action panel for FMCG template',
    icon: MousePointer,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'buttonText', 'pdfUrl'],
  },
  {
    type: 'roi-hero',
    label: 'ROI Hero Banner',
    description: 'Hero block with customizable colors and image 123.png',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'button1BgColor',
      'button1BorderColor',
      'button1Text',
      'button1TextColor',
      'button1Url', 'button1FormType',
      'button2BgColor',
      'button2BorderColor',
      'button2Text',
      'button2TextColor',
      'button2Url', 'button2FormType',
      'image'
    ],
  },
  {
    type: 'roi-explanation',
    label: 'ROI Explanation',
    description: 'What is ROI explanation block with writing notebook and purple cards',
    icon: Type,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['image', 'title', 'paragraphs', 'formulaText', 'cards'],
  },
  {
    type: 'roi-formula',
    label: 'ROI Formula',
    description: 'How to calculate ROI block with equation formulas image',
    icon: FileText,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'paragraphs', 'image1', 'image2'],
  },
  {
    type: 'roi-usage',
    label: 'ROI Usage & Details',
    description: 'Usage description, Limitations list, and ROI FAQs',
    icon: Layers,
    color: 'bg-[#4B2A63]/5 text-[#4B2A63]',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'usageTitle',
      'usageParagraphs',
      'usageImage',
      'limitationsTitle',
      'limitationsDescription',
      'limitations',
      'faqTitle',
      'faqs'
    ],
  },
  {
    type: 'oracle-hero',
    label: 'Oracle Migration Hero',
    description: 'Hero banner section with CMS styling configuration for the Oracle Upgrade page',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'button1BgColor',
      'button1BorderColor',
      'button1Text',
      'button1TextColor',
      'button1Url', 'button1FormType',
      'button2BgColor',
      'button2BorderColor',
      'button2Text',
      'button2TextColor',
      'button2Url', 'button2FormType',
      'image'
    ],
  },
  {
    type: 'oracle-partner',
    label: 'Oracle Trust Strip',
    description: '3-column partner strip displaying trust metrics and logo uploads',
    icon: Grid,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'image1',
      'text1',
      'title2',
      'description2',
      'image3',
      'text3'
    ],
  },
  {
    type: 'oracle-why-upgrade',
    label: 'Oracle Why Upgrade',
    description: '2-column section highlighting benefits with custom checkmark points',
    icon: Type,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['image', 'title', 'description', 'points'],
  },
  {
    type: 'oracle-migration-flow',
    label: 'Oracle Migration Stepper',
    description: 'Horizontal timeline stepper illustrating migration processes (01 to 05)',
    icon: Layers,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'steps'],
  },
  {
    type: 'oracle-framework',
    label: 'Oracle Upgrade Framework',
    description: '4-card grid showing upgrade framework',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'cards'],
  },
  {
    type: 'oracle-cta',
    label: 'Oracle Strategy CTA',
    description: 'Call to action banner with strategy roadmap',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'buttonText', 'pdfUrl'],
  },
  {
    type: 'bi-hero',
    label: 'BI Hero Banner',
    description: 'Hero banner section with CMS styling configuration for the Business Intelligence page',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'button1BgColor',
      'button1BorderColor',
      'button1Text',
      'button1TextColor',
      'button1Url', 'button1FormType',
      'button2BgColor',
      'button2BorderColor',
      'button2Text',
      'button2TextColor',
      'button2Url', 'button2FormType',
      'image'
    ],
  },
  {
    type: 'bi-intro',
    label: 'BI Intro Banner',
    description: 'Introductory banner with badge, title, and description for the BI page',
    icon: Type,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['badge', 'title', 'description'],
  },
  {
    type: 'bi-insights',
    label: 'BI Insights List',
    description: 'Two-column section with a list of key insights on the left and illustration on the right',
    icon: Layers,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'items', 'rightImage'],
  },
  {
    type: 'bi-tabs',
    label: 'BI Persona Tabs',
    description: 'Interactive persona tab switcher with questions and dashboard screenshot for BI page',
    icon: Layers,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['tabs'],
  },
  {
    type: 'bi-highlight-strip',
    label: 'BI Highlight Strip',
    description: 'Yellow callout strip with two key statements and round icons',
    icon: Grid,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['items']
  },
  {
    type: 'bi-business-impact',
    label: 'BI Business Impact Timeline',
    description: 'Vertical stepper timeline showcasing how the team addresses business problems',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'description', 'steps']
  },
  {
    type: 'bi-architecture',
    label: 'BI Architecture',
    description: 'Three-column data architecture flow chart with stages and detailed items',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'image']
  },
  {
    type: 'bi-empowerment',
    label: 'BI Empowerment',
    description: 'Leader empowerment grid block displaying benefits in dark cards',
    icon: Grid,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'cards']
  },
  {
    type: 'bi-industries',
    label: 'BI Industries Served',
    description: 'Sectors served by BI services with 2x2 grid of industry visuals',
    icon: Grid,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'industries']
  },
  {
    type: 'bi-industry-services',
    label: 'BI Services by Industry',
    description: 'Tab-switched vertical services section split between preview image and detailed bullet lists',
    icon: Grid,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'tabs']
  },
  {
    type: 'rpa-hero',
    label: 'RPA Hero',
    description: 'Hero section with customizable gradient background, title, description, dual buttons, and right-side flowchart illustration',
    icon: Layout,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeBgColor',
      'badgeText',
      'badgeTextColor',
      'title',
      'titleColor',
      'description',
      'descriptionColor',
      'button1BgColor',
      'button1Text',
      'button1TextColor',
      'button1Url', 'button1FormType',
      'button2BgColor',
      'button2BorderColor',
      'button2Text',
      'button2TextColor',
      'button2Url', 'button2FormType',
      'image'
    ]
  },
  {
    type: 'rpa-overview',
    label: 'RPA Overview & Stats',
    description: 'Overview text, metrics cards (fixed to 3 items), and partner logos',
    icon: FileText,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'subtitle', 'autoScroll', 'cards', 'logos']
  },
  {
    type: 'rpa-industries',
    label: 'RPA Industries',
    description: '12-column responsive grid showcasing how RPA empowers different industries',
    icon: Grid,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'industries']
  },
  {
    type: 'rpa-solutions',
    label: 'RPA Solutions',
    description: 'Next-gen RPA workflow solutions vertical list of tabs alongside mockup visual',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'solutions', 'image']
  },
  {
    type: 'rpa-frameworks',
    label: 'RPA Frameworks & Expertise',
    description: 'Logo strip for RPA frameworks (UiPath, Power Automate, etc.) with centered title',
    icon: FileText,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'autoScroll', 'logos']
  },
  {
    type: 'rpa-benefits',
    label: 'RPA Benefits',
    description: '6 responsive benefits cards with hover overlay effects and image backgrounds',
    icon: Grid,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'benefits']
  },
  {
    type: 'rpa-capabilities',
    label: 'RPA Capabilities',
    description: 'Circular diagram showing 6 core capabilities wrapping a central hub',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'items']
  },
  {
    type: 'rpa-faq',
    label: 'RPA FAQ',
    description: 'Robotic Process Automation FAQ accordion list',
    icon: FileText,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'subtitle', 'faqs']
  },
  {
    type: 'rpa-cta',
    label: 'RPA CTA',
    description: 'RPA page bottom conversion banner',
    icon: MousePointer,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'buttonText', 'pdfUrl'],
  },
  {
    type: 'oracle-apex-hero',
    label: 'Oracle APEX Hero',
    description: 'Hero section for Oracle Forms to Oracle APEX migration template with badge, title, description, and double buttons',
    icon: Layout,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'badgeText',
      'badgeBgColor',
      'badgeBorderColor',
      'badgeTextColor',
      'title',
      'titleTextColor',
      'description',
      'descriptionTextColor',
      'button1Text',
      'button1BgColor',
      'button1BorderColor',
      'button1TextColor',
      'button1Url', 'button1FormType',
      'button2Text',
      'button2BgColor',
      'button2BorderColor',
      'button2TextColor',
      'button2Url', 'button2FormType',
      'image'
    ]
  },
  {
    type: 'oracle-apex-intro',
    label: 'Oracle APEX Intro',
    description: 'Centered intro section for Oracle APEX template with title, multiple paragraphs, and a centered CTA button',
    icon: Type,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'paragraphs', 'buttonText', 'buttonUrl', 'buttonFormType']
  },
  {
    type: 'oracle-apex-why-migrate',
    label: 'Oracle APEX Why Migrate',
    description: '2-column benefits list for Oracle APEX template with dynamic points and left side image/tag card',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'description', 'tagText', 'points', 'image']
  },
  {
    type: 'oracle-apex-deliverables',
    label: 'Oracle APEX Deliverables',
    description: '2-column side-by-side What We Deliver and Business Impact lists on a purple background',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['leftTitle', 'leftItems', 'rightTitle', 'rightItems']
  },
  {
    type: 'oracle-apex-approach',
    label: 'Oracle APEX Approach Tabs',
    description: 'Tabbed section demonstrating Oracle Forms to Oracle APEX strategic migration approach with dynamic card switching',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['title', 'tag', 'description', 'tabs']
  },
  {
    type: 'oracle-apex-cta',
    label: 'Oracle APEX CTA',
    description: 'Call-to-action banner for the Oracle APEX migration template with a centered title, description, and button',
    icon: Layout,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['bgColor', 'title', 'titleColor', 'description', 'descriptionColor', 'buttonText', 'buttonBgColor', 'buttonTextColor', 'pdfUrl']
  },
  {
    type: 'europe-hero',
    label: 'Europe Hero',
    description: 'Centered hero with badge, dual CTAs, gradient background, and optional illustration for ebizframe ERP Europe landing page',
    icon: Layout,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'backgroundGradient',
      'badgeBorderColor', 'badgeBgColor', 'badgeText', 'badgeTextColor',
      'title', 'titleColor', 'description', 'descriptionColor',
      'primaryButtonBorderColor', 'primaryButtonBgColor', 'primaryButtonText', 'primaryButtonTextColor', 'primaryButtonUrl', 'primaryButtonFormType',
      'secondaryButtonBorderColor', 'secondaryButtonBgColor', 'secondaryButtonText', 'secondaryButtonTextColor', 'secondaryButtonUrl', 'secondaryButtonFormType',
      'heroIllustration', 'enableIllustration', 'enableAnimation',
      'hideSection', 'internalName', 'anchorId', 'backgroundColor', 'backgroundImage', 'containerWidth',
      'sectionPaddingTop', 'sectionPaddingBottom', 'theme', 'textAlignment', 'customClasses',
    ],
  },
  {
    type: 'europe-feature-cards',
    label: 'Europe Feature Cards',
    description: 'Grid of service/feature cards with image, title, description, and learn more link (max 12)',
    icon: Grid,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: ['cards'],
  },
  {
    type: 'europe-dark-showcase',
    label: 'Europe Dark Showcase',
    description: 'Dark full-width showcase with badge, CTAs, and dashboard image carousel',
    icon: Layers,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'badgeText',
      'title',
      'description',
      'primaryButtonText', 'primaryButtonUrl', 'primaryButtonFormType',
      'secondaryButtonText', 'secondaryButtonUrl', 'secondaryButtonFormType',
      'slides',
    ],
  },
  {
    type: 'europe-global-presence',
    label: 'Europe Global Presence',
    description: 'Split layout with world map image and statistics grid on dark background',
    icon: Users,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'image', 'subtitle', 'title', 'description', 'statistics',
    ],
  },
  {
    type: 'europe-case-study-slider',
    label: 'Europe Case Study Slider',
    description: 'Horizontal case study carousel with thumbnails, metrics, and navigation controls',
    icon: Briefcase,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'slides',
    ],
  },
  {
    type: 'europe-promo-cta',
    label: 'Europe Promotional CTA',
    description: 'Simple promotional call-to-action block with title, description, and button',
    icon: MousePointer,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'image', 'smallTitle', 'title', 'description', 'buttonText', 'buttonUrl', 'buttonFormType',
    ],
  },
  {
    type: 'europe-ai-monitor',
    label: 'Europe AI Monitor',
    description: 'Split layout with left aligned content and right aligned brand monitoring dashboard mockup',
    icon: ImageIcon,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'image', 'badgeText', 'title', 'description', 'buttonText', 'buttonUrl', 'buttonFormType',
    ],
  },
  {
    type: 'europe-product-showcase',
    label: 'Europe Product Showcase',
    description: 'Split layout with device mockup and feature list for mobile/product showcase',
    icon: ImageIcon,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'deviceImage', 'badgeText', 'title', 'description', 'buttonText', 'buttonUrl', 'buttonFormType', 'cards',
    ],
  },
  {
    type: 'europe-reports',
    label: 'Europe Insights / Reports',
    description: 'Three-column grid of insight and report cards with image, category, and title',
    icon: FileText,
    color: 'bg-violet-50 text-violet-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'sectionTitle', 'cards',
    ],
  },
  {
    type: 'uganda-hero',
    label: 'Uganda Hero',
    description: 'Header section with dynamic background gradient, centered badge, title, description, and primary/secondary button controls.',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'bgColor',
      'gradientColor1',
      'gradientColor2',
      'gradientColor3',
      'backgroundGradient',
      'badgeBorderColor', 'badgeBgColor', 'badgeText', 'badgeTextColor',
      'title', 'titleColor',
      'description', 'descriptionColor',
      'primaryButtonBorderColor', 'primaryButtonBgColor', 'primaryButtonText', 'primaryButtonTextColor', 'primaryButtonUrl', 'primaryButtonFormType',
      'secondaryButtonBorderColor', 'secondaryButtonBgColor', 'secondaryButtonText', 'secondaryButtonTextColor', 'secondaryButtonUrl', 'secondaryButtonFormType',
    ],
  },
  {
    type: 'uganda-presence',
    label: 'Uganda Presence',
    description: 'Map representation and horizontal grid of exactly 4 statistics cards.',
    icon: ImageIcon,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'image', 'stats',
    ],
  },
  {
    type: 'uganda-services',
    label: 'Uganda Services',
    description: 'Services grid with 4 colorful layout cards with custom images, title, description, and link features.',
    icon: Grid,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'badgeText', 'title', 'cards',
    ],
  },
  {
    type: 'uganda-control',
    label: 'Uganda Control',
    description: 'Split dashboard layout displaying governance features, description paragraph text, check items, and side graphic.',
    icon: ImageIcon,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'subtitle', 'title', 'desc1', 'desc2', 'points', 'image',
    ],
  },
  {
    type: 'uganda-capabilities',
    label: 'Uganda Capabilities',
    description: '3-column grid displaying exactly 6 white benefit/capability cards with icons.',
    icon: Grid,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'subtitle', 'title', 'description', 'cards',
    ],
  },
  {
    type: 'uganda-industries',
    label: 'Uganda Industries',
    description: '4-column grid showing industry sectors using full-bleed graphic image cards with text overlays.',
    icon: Grid,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'subtitle', 'title', 'description', 'cards',
    ],
  },
  {
    type: 'uganda-insights',
    label: 'Uganda Insights',
    description: 'Insights block with left vertical navigation menu and right side layout containing paragraphs, checklist items, and mockup graphics.',
    icon: Grid,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
    fieldOrder: [
      'tag', 'title', 'description', 'tabs',
    ],
  }
];


export function getSectionDefinition(type: string): SectionTypeDefinition | undefined {
  return SECTION_REGISTRY.find((s) => s.type === type);
}

export function isValidSectionType(type: string): boolean {
  return SECTION_REGISTRY.some((s) => s.type === type);
}
