import {
  Layout,
  Type,
  ImageIcon,
  Grid,
  Briefcase,
  FileText,
  MousePointer,
  Layers,
  LucideIcon,
} from 'lucide-react';

export interface SectionTypeDefinition {
  type: string;
  label: string;
  description: string;
  icon: LucideIcon;
  color: string;
  defaultVariant: string;
  supportsVariants: boolean;
}

export const SECTION_REGISTRY: SectionTypeDefinition[] = [
  {
    type: 'hero',
    label: 'Hero Banner',
    description: 'Main brand message and primary CTA',
    icon: Layout,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: true,
  },
  {
    type: 'trusted-brands',
    label: 'Brand Trust',
    description: 'Client logos and partner grid',
    icon: Grid,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'intro',
    label: 'Intro Text',
    description: 'Mission statement and key metrics',
    icon: Type,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'services',
    label: 'Services Grid',
    description: 'Core business offerings and solutions',
    icon: Briefcase,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: true,
  },
  {
    type: 'industries',
    label: 'Industries',
    description: 'Vertical specific solution blocks',
    icon: ImageIcon,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'why-ess',
    label: 'Value Prop',
    description: 'Unique selling points and differentiators',
    icon: MousePointer,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'portfolio',
    label: 'Portfolio',
    description: 'Case studies and project highlights',
    icon: Layers,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'blog',
    label: 'Resources',
    description: 'Latest news and thought leadership',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'rich_text',
    label: 'Rich Text',
    description: 'Flexible HTML content block',
    icon: FileText,
    color: 'bg-slate-50 text-slate-400',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'erp-hero',
    label: 'ERP Hero',
    description: 'Header block for ERP overview',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'erp-intro',
    label: 'ERP Overview Intro',
    description: 'General corporate intro text for ERP',
    icon: Type,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'erp-modules',
    label: 'ERP Modules Grid',
    description: 'Core functional capabilities grid',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'erp-features',
    label: 'ERP Tabbed Features',
    description: 'Interactive selector for technical capabilities',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'erp-value',
    label: 'ERP Business Value',
    description: 'Grid showcasing business capabilities',
    icon: MousePointer,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'erp-transform',
    label: 'ERP Workflow Stack',
    description: 'Vertical panels for strategic benefits',
    icon: FileText,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-hero',
    label: 'Retail Hero',
    description: 'Header block for Retail ERP overview',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-nurture',
    label: 'Retail Nurture',
    description: 'Nurture your business section',
    icon: Type,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-features',
    label: 'Retail Features',
    description: 'Dark-themed feature showcase',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-operations',
    label: 'Retail Operations Grid',
    description: 'Grid showcasing POS operations',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-mobile-dashboard',
    label: 'Retail Mobile Dashboard',
    description: 'Interactive accordion for modules',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'retail-clients',
    label: 'Retail Clients',
    description: 'Brand trust and client logos',
    icon: ImageIcon,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'mfg-hero',
    label: 'Manufacturing Hero',
    description: 'Hero block for Manufacturing template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'mfg-icons',
    label: 'Manufacturing Icons Row',
    description: 'Icons showcasing manufacturing benefits',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'mfg-demand',
    label: 'Manufacturing Connect Demand',
    description: 'Connect demand section',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'mfg-process',
    label: 'Manufacturing Process Flow',
    description: 'Manufacturing process flow steps',
    icon: Layout,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'mfg-efficiency',
    label: 'Manufacturing Efficiency Dash',
    description: 'Efficiency dashboard block',
    icon: FileText,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'mfg-models',
    label: 'Manufacturing Operating Models',
    description: 'Operating models grid',
    icon: Grid,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-hero',
    label: 'Career Hero',
    description: 'Hero block for Career template',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-why-join',
    label: 'Career Why Join',
    description: 'Why Join ESS section',
    icon: MousePointer,
    color: 'bg-rose-50 text-rose-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-offices',
    label: 'Career Offices',
    description: 'Global offices grid',
    icon: Grid,
    color: 'bg-amber-50 text-amber-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-experience',
    label: 'Career Experience',
    description: 'Software experience block',
    icon: Layers,
    color: 'bg-blue-50 text-blue-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-perks',
    label: 'Career Perks',
    description: 'Perks and benefits grid',
    icon: Grid,
    color: 'bg-emerald-50 text-emerald-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-life',
    label: 'Career Life',
    description: 'Life Beyond Code gallery',
    icon: ImageIcon,
    color: 'bg-cyan-50 text-cyan-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'job-detail-hero',
    label: 'Job Detail Hero',
    description: 'Header section for a specific job detail page',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'job-detail-content',
    label: 'Job Detail Content',
    description: 'Main content and application form for a job detail page',
    icon: FileText,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-positions',
    label: 'Career Open Positions',
    description: 'Open job positions list',
    icon: Briefcase,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'career-cta',
    label: 'Career CTA',
    description: 'Call to action for career',
    icon: Layout,
    color: 'bg-slate-50 text-slate-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'employee-spotlight-hero',
    label: 'Employee Spotlight Hero',
    description: 'Hero block for Employee Spotlight',
    icon: Layout,
    color: 'bg-indigo-50 text-indigo-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
  {
    type: 'employee-spotlight-cards',
    label: 'Employee Spotlight Cards',
    description: 'Cards showcasing employees for Spotlight',
    icon: Grid,
    color: 'bg-purple-50 text-purple-600',
    defaultVariant: 'default',
    supportsVariants: false,
  },
];

export function getSectionDefinition(type: string): SectionTypeDefinition | undefined {
  return SECTION_REGISTRY.find((s) => s.type === type);
}

export function isValidSectionType(type: string): boolean {
  return SECTION_REGISTRY.some((s) => s.type === type);
}
